[package]
name = "nyan_browser"
version = "0.1.0"
edition = "2021"

[dependencies]
webdriver = "0.46.0"
tokio = { version = "1.28", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
